Entity/Slide.php
<?php

namespace SmartCore\Module\Slider\Entity;

use Doctrine\ORM\Mapping as ORM;
use Smart\CoreBundle\Doctrine\ColumnTrait;
use Symfony\Component\HttpFoundation\File\UploadedFile;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity
 * @ORM\Table(name="slides",
 *      indexes={
 *          @ORM\Index(columns={"position"}),
 *          @ORM\Index(columns={"user_id"}),
 *      }
 * )
 */
class Slide
{
    use ColumnTrait\Id;
    use ColumnTrait\IsEnabled;
    use ColumnTrait\CreatedAt;
    use ColumnTrait\Position;
    use ColumnTrait\Title;
    use ColumnTrait\FosUser;

    /**
     * @Assert\File(maxSize="2000000")
     */
    private $file;

    /**
     * @var string
     *
     * @ORM\Column(length=64, unique=true)
     */
    private $file_name;

    /**
     * @var string
     *
     * @ORM\Column(length=255)
     */
    private $original_file_name;

    /**
     * @ORM\Column(type="array", nullable=true)
     */
    private $properties;

    /**
     * @var Slider
     *
     * @ORM\ManyToOne(targetEntity="Slider", inversedBy="slides")
     * @ORM\JoinColumn(name="slider_id", nullable=false)
     * @Assert\NotBlank()
     */
    private $slider;

    /**
     * Constructor.
     */
    public function __construct()
    {
        $this->created_at   = new \DateTime();
        $this->is_enabled   = true;
        $this->position     = 0;
        $this->properties   = [];
    }

    /**
     * @param string $file_name
     *
     * @return $this
     */
    public function setFileName($file_name)
    {
        $this->file_name = $file_name;

        return $this;
    }

    /**
     * @return string
     */
    public function getFileName()
    {
        return $this->file_name;
    }

    /**
     * @param string $original_file_name
     *
     * @return $this
     */
    public function setOriginalFileName($original_file_name)
    {
        $this->original_file_name = $original_file_name;

        return $this;
    }

    /**
     * @return string
     */
    public function getOriginalFileName()
    {
        return $this->original_file_name;
    }

    /**
     * @param \SmartCore\Module\Slider\Entity\Slider $slider
     *
     * @return $this
     */
    public function setSlider(Slider $slider)
    {
        $this->slider = $slider;

        return $this;
    }

    /**
     * @return \SmartCore\Module\Slider\Entity\Slider
     */
    public function getSlider()
    {
        return $this->slider;
    }

    /**
     * @param mixed $properties
     *
     * @return $this
     */
    public function setProperties($properties)
    {
        $this->properties = $properties;

        return $this;
    }

    /**
     * @return mixed
     */
    public function getProperties()
    {
        return $this->properties;
    }

    /**
     * @param UploadedFile $file
     */
    public function setFile(UploadedFile $file = null)
    {
        $this->file = $file;
    }

    /**
     * @return UploadedFile
     */
    public function getFile()
    {
        return $this->file;
    }
}

Entity/Slider.php
<?php

namespace SmartCore\Module\Slider\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\ORM\Mapping as ORM;
use Smart\CoreBundle\Doctrine\ColumnTrait;

/**
 * @ORM\Entity
 * @ORM\Table(name="sliders")
 */
class Slider
{
    use ColumnTrait\Id;
    use ColumnTrait\Title;

    /**
     * @var int
     *
     * @ORM\Column(type="smallint", nullable=true)
     */
    private $width;

    /**
     * @var int
     *
     * @ORM\Column(type="smallint", nullable=true)
     */
    private $height;

    /**
     * Метод ресайза картинки (Imagine\Image\ManipulatorInterface::THUMBNAIL_INSET или THUMBNAIL_OUTBOUND),
     * если указан, тогда применяется с указанными размерами.
     *
     * @var string
     *
     * @ORM\Column(type="string", length=10, nullable=true)
     */
    private $mode;

    /**
     * @var string
     *
     * @ORM\Column(type="string", length=32, nullable=true)
     */
    private $library;

    /**
     * @var int
     *
     * @ORM\Column(type="integer")
     */
    protected $pause_time;

    /**
     * @var string
     *
     * @ORM\Column(type="text", nullable=true)
     */
    private $slide_properties;

    /**
     * @var Slide[]
     *
     * @ORM\OneToMany(targetEntity="Slide", mappedBy="slider")
     * @ORM\OrderBy({"position" = "ASC"})
     */
    protected $slides;

    /**
     * Constructor.
     */
    public function __construct()
    {
        $this->pause_time = 5000;
        $this->slides = new ArrayCollection();
    }

    /**
     * @return string
     */
    public function __toString()
    {
        return $this->getTitle();
    }

    /**
     * @param int $width
     *
     * @return $this
     */
    public function setWidth($width)
    {
        $this->width = $width;

        return $this;
    }

    /**
     * @return int
     */
    public function getWidth()
    {
        return $this->width;
    }

    /**
     * @param string $slide_properties
     *
     * @return $this
     */
    public function setSlideProperties($slide_properties)
    {
        $this->slide_properties = $slide_properties;

        return $this;
    }

    /**
     * @return string
     */
    public function getSlideProperties()
    {
        return $this->slide_properties;
    }

    /**
     * @param string $mode
     *
     * @return $this
     */
    public function setMode($mode)
    {
        $this->mode = $mode;

        return $this;
    }

    /**
     * @return string
     */
    public function getMode()
    {
        return $this->mode;
    }

    /**
     * @param string $library
     *
     * @return $this
     */
    public function setLibrary($library)
    {
        $this->library = $library;

        return $this;
    }

    /**
     * @return string
     */
    public function getLibrary()
    {
        return $this->library;
    }

    /**
     * @param int $pause_time
     *
     * @return $this
     */
    public function setPauseTime($pause_time)
    {
        $this->pause_time = $pause_time;

        return $this;
    }

    /**
     * @return int
     */
    public function getPauseTime()
    {
        return $this->pause_time;
    }

    /**
     * @param int $height
     *
     * @return $this
     */
    public function setHeight($height)
    {
        $this->height = $height;

        return $this;
    }

    /**
     * @return int
     */
    public function getHeight()
    {
        return $this->height;
    }

    /**
     * @param \SmartCore\Module\Slider\Entity\Slide[] $slides
     *
     * @return $this
     */
    public function setSlides($slides)
    {
        $this->slides = $slides;

        return $this;
    }

    /**
     * @return \SmartCore\Module\Slider\Entity\Slide[]
     */
    public function getSlides()
    {
        return $this->slides;
    }
}

Resources/views/Admin/index.html.twig
{% extends '@CMS/Admin/module.html.twig' %}

{% block title %}{{ 'Slider'|trans }} / {{ parent() }}{% endblock %}

{% set page_header = 'Slider'|trans %}
{% set page_description = 'Module'|trans %}

{% block content %}

    <ul class="nav nav-pills" id="myTab">
        <li class="active"><a>Список всех слайдеров</a></li>
    </ul>

<div class="box box-primary">
    <div class="box-header with-border">

    <div class="tab-content">
        <div class="tab-pane active" id="all">
            <table class="table table-bordered table-hover">
                <thead><tr>
                    <th style="width: 1%;">id</th>
                    <th>{{ 'Slider'|trans }}</th>
                    <th>{{ 'Dimension'|trans }}</th>
                    <th>{{ 'Pause time'|trans }}</th>
                    <th>{{ 'Library'|trans }}</th>
                    <th>{{ 'Actions'|trans }}</th>
                </tr></thead>
                <tbody>
                {% for slider in sliders %}
                    <tr>
                        <td>{{ slider.id }}</td>
                        <td><a href="{{ path('smart_module.slider.admin_slider', {'id': slider.id }) }}">{{ slider.title }}</a></td>
                        <td>{{ slider.width ~ 'x' ~ slider.height }}</td>
                        <td>{{ slider.pauseTime }}</td>
                        <td>{{ slider.library }}</td>
                        <td><a href="{{ path('smart_module.slider.admin_slider_edit', {'id': slider.id}) }}">Свойства слайдера</a></td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>

        </div>
    </div>

    </div>
</div>

    <h3>Создать новый слайдер</h3>

    {{ form(form, {'attr': {'class': 'form-horizontal well'}} ) }}

{% endblock content %}

Resources/views/Admin/slide_edit.html.twig
{% extends '@SliderModule/Admin/index.html.twig' %}

{% block title %}{{ 'Slide'|trans }} / {{ parent() }}{% endblock %}

{% block content %}

    <ul class="nav nav-pills" id="myTab">
        <li><a href="{{ path('smart_module.slider.admin') }}">Список всех слайдеров</a></li>
        <li><a href="{{ path('smart_module.slider.admin_slider', {'id': slide.slider.id }) }}">Редактирование слайдера <b>&laquo;{{ slide.slider.title }}&raquo;</b></a></li>
        <li class="active"><a>Свойства слайда</a></li>
    </ul>

<div class="box box-primary">
    <div class="box-header with-border">

    <table style="width: 100%;">
        <tr>
            <td style="vertical-align: top;">
                {{ form(form, {'attr': {'class': 'form-horizontal'}} ) }}
            </td>
            <td>
                <img src="{{ asset(webPath) }}{{ slide.filename }}" alt="" width="500" style="margin-left: 40px;" />
            </td>
        </tr>
    </table>

    </div>
</div>

{% endblock content %}

Resources/views/Admin/slider.html.twig
{% extends '@SliderModule/Admin/index.html.twig' %}

{% block title %}{{ 'Slider'|trans }} &laquo;{{ slider.title }}&raquo; / {{ parent() }}{% endblock %}

{% block content %}

    {% if folderPath %}
        <a class="btn btn-default btn-small btn-sm" href="{{ folderPath }}" title="{{ app.request.host ~ folderPath }}" style="float: right; margin-top: 8px;">
            <i class="icon-home"></i><span class="glyphicon glyphicon-home" aria-hidden="true"></span> Перейти на страницу слайдера на сайте
        </a>
    {% endif %}

    <ul class="nav nav-pills" id="myTab">
        <li><a href="{{ path('smart_module.slider.admin') }}">Список всех слайдеров</a></li>
        <li class="active"><a href="{{ path('smart_module.slider.admin_slider', {'id': slider.id }) }}">Редактирование слайдера <b>&laquo;{{ slider.title }}&raquo;</b></a></li>
        <li><a href="{{ path('smart_module.slider.admin_slider_edit', {'id': slider.id}) }}">{{ 'Slider settings'|trans }}</a></li>
    </ul>

<div class="box box-primary">
    <div class="box-header with-border">

    <div class="tab-content">
        <div class="tab-pane active" id="all">
            <table class="table table-bordered table-hover">
                <thead><tr>
                    <th style="width: 1%;">id</th>
                    <th>{{ 'Slide'|trans }}</th>
                    <th>{{ 'Position'|trans }}</th>
                    <th>{{ 'Title'|trans }}</th>
                    <th>{{ 'Original filename'|trans }}</th>
                    <th>{{ 'Status'|trans }}</th>
                    <th>{{ 'Created'|trans }}</th>
                </tr></thead>
                <tbody>
                {% for slide in slider.slides %}
                    <tr>
                        <td>{{ slide.id }}</td>
                        <td><a href="{{ path('smart_module.slider.admin_slider_item_edit', {'id': slide.id}) }}"><img src="{{ asset(webPath) }}{{ slide.filename }}" alt="" width="100" /></a></td>
                        <td>{{ slide.position }}</td>
                        <td>{{ slide.title }}</td>
                        <td>{{ slide.originalFileName }}</td>
                        <td>
                            {% if slide.enabled %}
                                <span class="label label-success">Включен</span>
                            {% else %}
                                <span class="label label-danger label-important">Отключен</span>
                            {% endif %}
                        </td>
                        <td>{{ slide.createdAt|localizeddate('long') }}</td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>

        </div>
    </div>

    </div>
</div>

    <h3>Загрузить картинку</h3>

    {{ form(form, {'attr': {'class': 'form-horizontal well'}} ) }}

{% endblock content %}

Resources/views/Admin/slider_edit.html.twig
{% extends '@SliderModule/Admin/index.html.twig' %}

{% block title %}{{ 'Slider settings'|trans }} / {{ parent() }}{% endblock %}

{% block content %}

    <ul class="nav nav-pills" id="myTab">
        <li><a href="{{ path('smart_module.slider.admin') }}">Список всех слайдеров</a></li>
        <li><a href="{{ path('smart_module.slider.admin_slider', {'id': slider.id }) }}">Редактирование слайдера <b>&laquo;{{ slider.title }}&raquo;</b></a></li>
        <li class="active"><a href="{{ path('smart_module.slider.admin_slider_edit', {'id': slider.id}) }}">{{ 'Slider settings'|trans }}</a></li>
    </ul>

<div class="box box-primary">
    <div class="box-header with-border">

    {{ form(form, {'attr': {'class': 'form-horizontal well'}} ) }}

    </div>
</div>

{% endblock content %}